# This workflow will build the native component for different platforms using
# qemu-user & docker

name: Build Linux Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  native:

    # Switch back to ubuntu-latest after that maps to 20.04
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        arch:
          - "386"
          - amd64
          - arm
          - arm64
          - linux-arm-v5
          # this build does not work and ends up just rebuilding x86_64
          #- s390x
      fail-fast: false

    name: Linux binary ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Update System
        run: sudo apt-get update -y
      - name: Install qemu
        run: sudo apt-get install -y --no-install-recommends qemu-user-static
      - name: Experimental Docker
        run: sudo cp .github/experimental-docker.json /etc/docker/daemon.json
      - name: Restart Docker
        run: sudo systemctl restart docker.service
      - name: Define docker image
        id: dockersetup
        run: |
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            echo "DOCKER_IMAGE=amazoncorretto:8" >> "$GITHUB_OUTPUT"
            echo "DOCKER_SCRIPT=build-native-amazonlinux.sh" >> "$GITHUB_OUTPUT"
          else
            echo "DOCKER_IMAGE=debian:8" > "$GITHUB_OUTPUT"
            echo "DOCKER_SCRIPT=build-native-debian.sh" >> "$GITHUB_OUTPUT"
          fi
          echo "DOCKER_ARCH=$(echo ${{ matrix.arch }} | sed 's|-|/|g')" >> "$GITHUB_OUTPUT"
      - name: Pull docker image
        env:
          DOCKER_ARCH: ${{ steps.dockersetup.outputs.DOCKER_ARCH }}
          DOCKER_IMAGE: ${{ steps.dockersetup.outputs.DOCKER_IMAGE }}
        run: docker pull --platform $DOCKER_ARCH $DOCKER_IMAGE || true
      - name: Build inside Docker
        env:
          DOCKER_IMAGE: ${{ steps.dockersetup.outputs.DOCKER_IMAGE }}
          DOCKER_SCRIPT: ${{ steps.dockersetup.outputs.DOCKER_SCRIPT }}
        run: docker run --rm -v $GITHUB_WORKSPACE:/work $DOCKER_IMAGE /work/.github/$DOCKER_SCRIPT
      - name: Archive built library
        uses: actions/upload-artifact@v2
        with:
          name: shared-object-${{ matrix.arch }}
          path: build/jni/*.so
      - name: Archive built jar
        uses: actions/upload-artifact@v2
        with:
          name: jar-${{ matrix.arch }}
          path: archive/*.jar

